name: aethor_app
description: App mobile para citações estoicas diárias
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  app_links: ^6.3.2
  firebase_analytics: ^11.3.6
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_timezone: ^4.1.1
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  uuid: ^4.4.2
  in_app_purchase: ^3.2.0
  permission_handler: ^11.3.0
  phosphor_flutter: ^2.1.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
    image_path: "assets/images/aethor_icon.png"
  web:
    generate: true
    image_path: "assets/images/aethor_icon.png"
  windows:
    generate: true
    image_path: "assets/images/aethor_icon.png"
  image_path: "assets/images/aethor_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/aethor_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cormorant Garamond
      fonts:
        - asset: assets/fonts/CormorantGaramond-VariableFont_wght.ttf
        - asset: assets/fonts/CormorantGaramond-Italic-VariableFont_wght.ttf
          style: italic
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
