name: estoicismo_app
description: App mobile para citações estoicas diárias
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  flutter_timezone: ^4.1.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Cormorant Garamond
      fonts:
        - asset: assets/fonts/CormorantGaramond-VariableFont_wght.ttf
        - asset: assets/fonts/CormorantGaramond-Italic-VariableFont_wght.ttf
          style: italic
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
